api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core-runtime"
  name = ".NETCore Runtime Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "dotnet-runtime"
    sha256 = "da7107f758f912563b4ab27507fd112d5df0dd5fda0bfb0b1ac5cb738b5d5d39"
    source = "https://download.visualstudio.microsoft.com/download/pr/5f7daa05-c09f-41c3-b607-eabeefb6b677/1effcfea7b7f5208de533db8686f6e0f/dotnet-runtime-2.1.14-linux-x64.tar.gz"
    source_sha256 = "2350dc4c68f2110930996e84c64b3e82d8a623c959e0138df92807a9d35a3877"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime.2.1.14.linux-amd64-any-stack-da7107f7.tar.xz"
    version = "2.1.14"

  [[metadata.dependencies]]
    id = "dotnet-runtime"
    sha256 = "d97abbf8bde59c16091193d2646c3bafef32f8dc34ee7cd4771e4a1218578f54"
    source = "https://download.visualstudio.microsoft.com/download/pr/d2fb0b54-01ce-452c-b2a2-86dbef286265/055ad7740827cbe862d14ceb7ea54fac/dotnet-runtime-2.1.15-linux-x64.tar.gz"
    source_sha256 = "089becb6063b2577d51fc5f09e61e2c0f896c36b2854b6d53a1ab7762b7a6cb6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime.2.1.15.linux-amd64-any-stack-d97abbf8.tar.xz"
    version = "2.1.15"

  [[metadata.dependencies]]
    id = "dotnet-runtime"
    sha256 = "e494f3e495e7c7be90b1b8a908e57b08a6b19800fa5bc32f72028c3a28314bc0"
    source = "https://download.visualstudio.microsoft.com/download/pr/7647815e-9c28-40a5-96ea-c6ac4ebe2020/c026b1e93a5d6750a7666d3fe36a87f5/dotnet-runtime-3.0.2-linux-x64.tar.gz"
    source_sha256 = "aa091358e94519d50ab4f923d7e6877bf1e43d0972a57128206347421691c12b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime.3.0.2.linux-amd64-any-stack-e494f3e4.tar.xz"
    version = "3.0.2"

  [[metadata.dependencies]]
    id = "dotnet-runtime"
    sha256 = "c04c57d38653234b0bf9d67910aaa16f2428b1f052ae8755e4e9e3159d7bf957"
    source = "https://download.visualstudio.microsoft.com/download/pr/6ad304ea-28a3-41c6-b30f-f0e1393f41de/83af63265fd59a8bf171417bd5134bb6/dotnet-runtime-3.0.3-linux-x64.tar.gz"
    source_sha256 = "1867cfc12bbb7b6c993960f7874428762767badd81431a783a1b3f0c1d3bc82c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime.3.0.3.linux-amd64-any-stack-c04c57d3.tar.xz"
    version = "3.0.3"

  [[metadata.dependencies]]
    id = "dotnet-runtime"
    sha256 = "70b27eb07bdcefe2b1ec50fabae8f65d87735f2d4209bd2caa811ec4eb202dd4"
    source = "https://download.visualstudio.microsoft.com/download/pr/5d139dff-4ca0-4e0c-a68b-0976281d5b2d/d306f725466e058842faa25bf1b2f379/dotnet-runtime-3.1.0-linux-x64.tar.gz"
    source_sha256 = "3fd138add3787c5edf6446245b821dbe0b4acae032c2b9a4cc2b8eac2d9b9997"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime.3.1.0.linux-amd64-any-stack-70b27eb0.tar.xz"
    version = "3.1.0"

  [[metadata.dependencies]]
    id = "dotnet-runtime"
    sha256 = "6cb244edb9899f3d23d029034b39ad3563ee7bd2147ef27956dc31d58a14c517"
    source = "https://download.visualstudio.microsoft.com/download/pr/e060c2eb-1476-4d70-857c-24f5eead2070/ff0e007b7373c04f754b3818ffdb2134/dotnet-runtime-3.1.1-linux-x64.tar.gz"
    source_sha256 = "e049ceeeb912e873534fb0871b3b147deae59dc315236c69731a168d6639adae"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime.3.1.1.linux-amd64-any-stack-6cb244ed.tar.xz"
    version = "3.1.1"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-08-21T00:00:00Z
    link = "https://dotnet.microsoft.com/platform/support/policy/dotnet-core"
    name = "dotnet-runtime"
    version_line = "2.1.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2020-03-03T00:00:00Z
    link = "https://dotnet.microsoft.com/platform/support/policy/dotnet-core"
    name = "dotnet-runtime"
    version_line = "3.0.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2022-12-03T00:00:00Z
    link = "https://dotnet.microsoft.com/platform/support/policy/dotnet-core"
    name = "dotnet-runtime"
    version_line = "3.1.x"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
