api = "0.2"

[buildpack]
  id = "paketo-buildpacks/dotnet-core-runtime"
  name = "Paketo .NET Core Runtime Buildpack"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-runtime"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-21T00:00:00Z"
    id = "dotnet-runtime"
    sha256 = "40941b3739fb3daa7e4f5c5243dd5f884f8c78e2ef924010cfd9dc3da72398d3"
    source = "https://download.visualstudio.microsoft.com/download/pr/e52a08ae-0a98-4dbf-b371-bf50815ae05a/48e4eb969aee8df978fa2f32b743ae76/dotnet-runtime-2.1.23-linux-x64.tar.gz"
    source_sha256 = "d17845dd0bf39f73ff40e0d2250a56e8a03a1b3e3d06a9f877a135f62c2e9694"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_2.1.23_linux_x64_any-stack_40941b37.tar.xz"
    version = "2.1.23"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-21T00:00:00Z"
    id = "dotnet-runtime"
    sha256 = "14b24b9aab1d45f63006d81794d24f8accebdce8aff752335b7102fe017f3ffb"
    source = "https://download.visualstudio.microsoft.com/download/pr/e12e29fe-d4ca-4be6-9d24-69648c16e47e/1cf6bdba50135a72f64ef9dc34dfa784/dotnet-runtime-2.1.24-linux-x64.tar.gz"
    source_sha256 = "6568108ca10ef401d6a823b9d6132a12125db942eb4a7fe714f60ac2d2c672fe"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_2.1.24_linux_x64_any-stack_14b24b9a.tar.xz"
    version = "2.1.24"

  [[metadata.dependencies]]
    deprecation_date = "2022-12-04T00:00:00Z"
    id = "dotnet-runtime"
    sha256 = "45c52c881bd6c9cbe8bd0b48fb4f2f71dd9ad9ae2124ce2ccc74efc82ad09064"
    source = "https://download.visualstudio.microsoft.com/download/pr/fb8a9fd4-c015-4c0e-a478-6da0b590bc39/d831b206c30e0aa23501b4a210dec9b1/dotnet-runtime-3.1.9-linux-x64.tar.gz"
    source_sha256 = "72417009bb23a7eaba88af4844d9e2aec6ce3ed8cdb5c14480c861fd417aaac5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_3.1.9_linux_x64_any-stack_45c52c88.tar.xz"
    version = "3.1.9"

  [[metadata.dependencies]]
    deprecation_date = "2022-12-04T00:00:00Z"
    id = "dotnet-runtime"
    sha256 = "c241f236fccf8813f8d3be92ef26e06b695dc8d4305e480f74e76f8c1dd3c62b"
    source = "https://download.visualstudio.microsoft.com/download/pr/9ca38d86-ce96-4647-8f27-a5807ac42d6a/081194806997d3152be461259cb0bdd2/dotnet-runtime-3.1.10-linux-x64.tar.gz"
    source_sha256 = "991183e5551037d76f71910059e3e0b74e0806dfdbcf068e0c15cb46c0ae3349"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_3.1.10_linux_x64_any-stack_c241f236.tar.xz"
    version = "3.1.10"

  [[metadata.dependencies]]
    id = "dotnet-runtime"
    sha256 = "e684505482712c3c2edc689d2619a5460d0c0842f606d2809c97363b0d60a66d"
    source = "https://download.visualstudio.microsoft.com/download/pr/c84d49aa-200c-4400-a517-87cce5b7516d/94c89b00380eb212e19538b05f8cb968/dotnet-runtime-5.0.0-linux-x64.tar.gz"
    source_sha256 = "8d1b27cc293cc706a6852508405b803a50c8898a0f1e901ded16baa88d2d463f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_5.0.0_linux_x64_any-stack_e6845054.tar.xz"
    version = "5.0.0"

  [[metadata.dependencies]]
    id = "dotnet-runtime"
    sha256 = "6784f2f48a524fad34775743a5097598dc42742bbb8cb77232e9019a6b2b0b11"
    source = "https://download.visualstudio.microsoft.com/download/pr/1b2c8490-04c5-4c54-a05d-dbe4dd6c3f2c/85c2939a81302dcc822e01b5175c153e/dotnet-runtime-5.0.1-linux-x64.tar.gz"
    source_sha256 = "ac60d9309de77a20ff77960eae1ee783fb4fb14313686213ba5a4508fa0d6428"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_5.0.1_linux_x64_any-stack_6784f2f4.tar.xz"
    version = "5.0.1"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-08-21T00:00:00Z
    link = "https://dotnet.microsoft.com/platform/support/policy/dotnet-core"
    name = "dotnet-runtime"
    version_line = "2.1.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2022-12-04T00:00:00Z
    link = "https://dotnet.microsoft.com/platform/support/policy/dotnet-core"
    name = "dotnet-runtime"
    version_line = "3.1.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
