api = "0.2"

[buildpack]
  id = "paketo-buildpacks/dotnet-core-runtime"
  name = "Paketo .NET Core Runtime Buildpack"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-runtime"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-21T00:00:00Z"
    id = "dotnet-runtime"
    sha256 = "81711e4edea078a4115a67e908591f813ee22b7934f735d7bd6e9e15e906bdfb"
    source = "https://download.visualstudio.microsoft.com/download/pr/926c221c-a9bd-4022-a0bd-52f93d273883/a8582353d501c69bd991c52a52d79bae/dotnet-runtime-2.1.22-linux-x64.tar.gz"
    source_sha256 = "d4faaaed24b9bf5afaa6a777343dccbd6a05f267541b857d02ca16146dc54a2d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_2.1.22_linux_x64_any-stack_81711e4e.tar.xz"
    version = "2.1.22"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-21T00:00:00Z"
    id = "dotnet-runtime"
    sha256 = "40941b3739fb3daa7e4f5c5243dd5f884f8c78e2ef924010cfd9dc3da72398d3"
    source = "https://download.visualstudio.microsoft.com/download/pr/e52a08ae-0a98-4dbf-b371-bf50815ae05a/48e4eb969aee8df978fa2f32b743ae76/dotnet-runtime-2.1.23-linux-x64.tar.gz"
    source_sha256 = "d17845dd0bf39f73ff40e0d2250a56e8a03a1b3e3d06a9f877a135f62c2e9694"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_2.1.23_linux_x64_any-stack_40941b37.tar.xz"
    version = "2.1.23"

  [[metadata.dependencies]]
    deprecation_date = "2022-12-04T00:00:00Z"
    id = "dotnet-runtime"
    sha256 = "c241f236fccf8813f8d3be92ef26e06b695dc8d4305e480f74e76f8c1dd3c62b"
    source = "https://download.visualstudio.microsoft.com/download/pr/9ca38d86-ce96-4647-8f27-a5807ac42d6a/081194806997d3152be461259cb0bdd2/dotnet-runtime-3.1.10-linux-x64.tar.gz"
    source_sha256 = "991183e5551037d76f71910059e3e0b74e0806dfdbcf068e0c15cb46c0ae3349"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_3.1.10_linux_x64_any-stack_c241f236.tar.xz"
    version = "3.1.10"

  [[metadata.dependencies]]
    deprecation_date = "2022-12-04T00:00:00Z"
    id = "dotnet-runtime"
    sha256 = "a22a3b94c7d6dc50e0cc122de30943fe1145edc88c844411cfffe1740db6cc55"
    source = "https://download.visualstudio.microsoft.com/download/pr/a3575ea2-ce06-4002-8568-e887da3e3a4f/7991b9bb111edcd2114efc6fe3ebfabb/dotnet-runtime-3.1.11-linux-x64.tar.gz"
    source_sha256 = "8ff244b9e23bda79dbaba7823f9b738f3971700aeaa42a43e6f33156e6dd93f1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_3.1.11_linux_x64_any-stack_a22a3b94.tar.xz"
    version = "3.1.11"

  [[metadata.dependencies]]
    id = "dotnet-runtime"
    sha256 = "6784f2f48a524fad34775743a5097598dc42742bbb8cb77232e9019a6b2b0b11"
    source = "https://download.visualstudio.microsoft.com/download/pr/1b2c8490-04c5-4c54-a05d-dbe4dd6c3f2c/85c2939a81302dcc822e01b5175c153e/dotnet-runtime-5.0.1-linux-x64.tar.gz"
    source_sha256 = "ac60d9309de77a20ff77960eae1ee783fb4fb14313686213ba5a4508fa0d6428"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_5.0.1_linux_x64_any-stack_6784f2f4.tar.xz"
    version = "5.0.1"

  [[metadata.dependencies]]
    id = "dotnet-runtime"
    sha256 = "40111d4d726f9acf8c86074db459b39ded45260a1aa37deec5e17fb472d1ce1a"
    source = "https://download.visualstudio.microsoft.com/download/pr/824175f2-5577-46ec-a675-95d2f652575f/07dafc2398e669afa7d25f2d47398c36/dotnet-runtime-5.0.2-linux-x64.tar.gz"
    source_sha256 = "c39ae5cc5d72d4ce1fccb686a3240b27044ccf789719e989b8aafdf9af5099c3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_5.0.2_linux_x64_any-stack_40111d4d.tar.xz"
    version = "5.0.2"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-08-21T00:00:00Z
    link = "https://dotnet.microsoft.com/platform/support/policy/dotnet-core"
    name = "dotnet-runtime"
    version_line = "2.1.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2022-12-04T00:00:00Z
    link = "https://dotnet.microsoft.com/platform/support/policy/dotnet-core"
    name = "dotnet-runtime"
    version_line = "3.1.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
