api = 0.2

[buildpack]
id = "org.cloudfoundry.dotnet-core-runtime"
name = ".NETCore Runtime Buildpack"
version = "{{ .Version }}"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml","go.mod","go.sum"]
pre_package = "./scripts/build.sh"

[[metadata.dependencies]]
id = "dotnet-runtime"
sha256 = "050ef84312785800b55b1a5aec7ea398ad20908f94f7ba722285e02885ccc4ba"
source = "https://github.com/dotnet/cli/archive/729b316c13bf9289b033272c07c7dfd046ffbcaf.tar.gz"
source_sha256 = "1e2463cc161ae8f516aa047b09bef29aff6732f8346626b312b3acd75e9191ba"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime.2.2.6.linux-amd64-cflinuxfs3-050ef843.tar.xz"
version = "2.2.6"

[[metadata.dependency_deprecation_dates]]
date = 2019-12-23T00:00:00Z
link = "https://dotnet.microsoft.com/platform/support/policy/dotnet-core"
name = "dotnet-runtime"
version_line = "2.2.x"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
