api = "0.2"

[buildpack]
  id = "paketo-buildpacks/dotnet-core-runtime"
  name = "Paketo .NET Core Runtime Buildpack"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-runtime"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-21T00:00:00Z"
    id = "dotnet-runtime"
    sha256 = "36c68f7af89c95795dc8f30b1774e3f8fb2c0c11c369f26f9971774459a96f05"
    source = "https://download.visualstudio.microsoft.com/download/pr/19203a52-0453-4c37-b964-05ab5ca0e67c/0db9cc5de1de804740734ddb39cedb0a/dotnet-runtime-2.1.25-linux-x64.tar.gz"
    source_sha256 = "8540b85243a467e35db89ed5a933076022c416b13d4a35fcce8c8204596a8cc6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_2.1.25_linux_x64_any-stack_36c68f7a.tar.xz"
    version = "2.1.25"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-21T00:00:00Z"
    id = "dotnet-runtime"
    sha256 = "841c94bf12c0f6410c30191c7d647c2459704c6393fc0d94734748c61766e57d"
    source = "https://download.visualstudio.microsoft.com/download/pr/5c00bafe-4ead-4e9a-82b6-884a9727e751/fdb7f6701e556d89b6884037cc9983cb/dotnet-runtime-2.1.26-linux-x64.tar.gz"
    source_sha256 = "2a7e4d28c9ab479570e5d351257796db8fa1d13a95092eeebf3934260b9a7a6e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_2.1.26_linux_x64_any-stack_841c94bf.tar.xz"
    version = "2.1.26"

  [[metadata.dependencies]]
    deprecation_date = "2022-12-04T00:00:00Z"
    id = "dotnet-runtime"
    sha256 = "92a72d2f3bf35fc3780c3095d7cc567e46880796fd6cb5975962d9a4977bdbe1"
    source = "https://download.visualstudio.microsoft.com/download/pr/f54a9098-69e6-4914-8fa8-42cb4ed05e65/9daae40d4a0ea4ad7aa2fc014b5f20db/dotnet-runtime-3.1.12-linux-x64.tar.gz"
    source_sha256 = "3c9fc21b409654f42f9718fdb699847db268c695a56ce15839487587285d2f88"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_3.1.12_linux_x64_any-stack_92a72d2f.tar.xz"
    version = "3.1.12"

  [[metadata.dependencies]]
    deprecation_date = "2022-12-04T00:00:00Z"
    id = "dotnet-runtime"
    sha256 = "e154e5658ed1ea7d48df7313c5305cd90a46ffbade29431c1827dc098c92cfe5"
    source = "https://download.visualstudio.microsoft.com/download/pr/6880db3b-a4fe-4801-8e80-bbbec045f7c0/283b70d5e263c0341f011adf5a2ea5b1/dotnet-runtime-3.1.13-linux-x64.tar.gz"
    source_sha256 = "4e8e308934a56f8e9b55f895642ac39297465facbd2154651bd69fdbd50db996"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_3.1.13_linux_x64_any-stack_e154e565.tar.xz"
    version = "3.1.13"

  [[metadata.dependencies]]
    id = "dotnet-runtime"
    sha256 = "40111d4d726f9acf8c86074db459b39ded45260a1aa37deec5e17fb472d1ce1a"
    source = "https://download.visualstudio.microsoft.com/download/pr/824175f2-5577-46ec-a675-95d2f652575f/07dafc2398e669afa7d25f2d47398c36/dotnet-runtime-5.0.2-linux-x64.tar.gz"
    source_sha256 = "c39ae5cc5d72d4ce1fccb686a3240b27044ccf789719e989b8aafdf9af5099c3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_5.0.2_linux_x64_any-stack_40111d4d.tar.xz"
    version = "5.0.2"

  [[metadata.dependencies]]
    id = "dotnet-runtime"
    sha256 = "e912e2a968bf17159a0f729f96fdfc7a82bae9bddbbd2b1ee2d46cfd5d21306b"
    source = "https://download.visualstudio.microsoft.com/download/pr/49cc8956-3b51-42ff-a718-0fe6326e2fe5/9c3b23c1b92f0b3a8f9d6c2e3e72095e/dotnet-runtime-5.0.3-linux-x64.tar.gz"
    source_sha256 = "2677002b5d8e4103ce0381805004f11dc991804b17138a498e845ec0f26bb89e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_5.0.3_linux_x64_any-stack_e912e2a9.tar.xz"
    version = "5.0.3"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-08-21T00:00:00Z
    link = "https://dotnet.microsoft.com/platform/support/policy/dotnet-core"
    name = "dotnet-runtime"
    version_line = "2.1.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2022-12-04T00:00:00Z
    link = "https://dotnet.microsoft.com/platform/support/policy/dotnet-core"
    name = "dotnet-runtime"
    version_line = "3.1.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
