api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core-runtime"
name = ".NETCore Runtime Buildpack"
version = "{{ .Version }}"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml","go.mod","go.sum"]
pre_package = "./scripts/build.sh"

[[metadata.dependencies]]
id = "dotnet-runtime"
sha256 = "62894e472cdcb150e9f39e690d6117d57dcc2b4d35e3df7cc8be7419f5c7556a"
source = "https://download.visualstudio.microsoft.com/download/pr/5c1334bc-bd26-4232-a745-2728b36a2628/8e163216cdcec15332ebf2e5575962de/dotnet-runtime-2.1.6-linux-x64.tar.gz/archive/.tar.gz"
source_sha256 = "b7c56119afb73c31f1cebb53cad758685850c248d44fdfc571af26390f53635b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime.2.1.6.linux-amd64-cflinuxfs3-62894e47.tar.xz"
version = "2.1.6"

[[metadata.dependencies]]
id = "dotnet-runtime"
sha256 = "bd5dedeadc0bb1386e930ca2a870c0af30e289af2832332246ef118cbb2acc23"
source = "https://download.visualstudio.microsoft.com/download/pr/eae50d35-ec30-4416-829a-36e8b5158f22/52d8370bea6e696cee4280bec0eda4bc/dotnet-runtime-2.1.8-linux-x64.tar.gz/archive/.tar.gz"
source_sha256 = "990110e1c166fa3a90d57ebf13dd3c1ab0a4b47f8c3e1b5b06e9a8dde1a05840"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime.2.1.8.linux-amd64-cflinuxfs3-bd5dedea.tar.xz"
version = "2.1.8"

[[metadata.dependencies]]
id = "dotnet-runtime"
sha256 = "a189e542b469177bb4670b97657e34b907f7939ffa975dbf549382dffe2de7c7"
source = "https://download.visualstudio.microsoft.com/download/pr/c97de534-1959-4eba-a7fe-bb86b3bb5bf0/fb39bc9e2ac40cb2268e6fe509cbcecd/dotnet-runtime-2.1.9-linux-x64.tar.gz/archive/.tar.gz"
source_sha256 = "22938c1d3827d25afa16c280a2457e356e21f43ecd5a4f538825298dd9a3dec7"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime.2.1.9.linux-amd64-cflinuxfs3-a189e542.tar.xz"
version = "2.1.9"

[[metadata.dependencies]]
id = "dotnet-runtime"
sha256 = "1f7cda10f1b7acc22612e6d93e837a1e5222b976df879090678047813a1034d0"
source = "https://download.visualstudio.microsoft.com/download/pr/dd164132-d4c4-4c1a-8233-a4fc7e157935/bffa5312d613cab1a14f0858f947a6fc/dotnet-runtime-2.1.11-linux-x64.tar.gz/archive/.tar.gz"
source_sha256 = "02a13a92d672a9631f8b9065ca045be226e5364fab97183d95eb40f600a9d726"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime.2.1.11.linux-amd64-cflinuxfs3-1f7cda10.tar.xz"
version = "2.1.11"

[[metadata.dependencies]]
id = "dotnet-runtime"
sha256 = "f00cdbc21bcd581b719bdb5ed89048374cbcceac76d9913e2fe43454ed3632be"
source = "https://github.com/dotnet/cli/archive/243f6de49b3c4c16dd1a6413c39f463fcbdcf58d.tar.gz"
source_sha256 = "47e87c339c0069b6f487fa7077d7db41eff18d9334b1753d885d6568062b45cc"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime.2.1.12.linux-amd64-cflinuxfs3-f00cdbc2.tar.xz"
version = "2.1.12"

[[metadata.dependencies]]
id = "dotnet-runtime"
sha256 = "1879da5f9cd2d3fe3e39beec21daf5eaf19df34a9d6378c13f1fce7434d74b9f"
source = "https://github.com/dotnet/cli/archive/9b0b46aacc95a4e12fa7df23aa2c19dec1dacc03.tar.gz"
source_sha256 = "ecedcefdf5d8090e83c4f150ea2fa802f5dd92a2c3e1bb23b82a69fe1a9c9f18"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime.2.1.13.linux-amd64-cflinuxfs3-1879da5f.tar.xz"
version = "2.1.13"

[[metadata.dependencies]]
id = "dotnet-runtime"
sha256 = "4f43b75b0662254fd29213ba4068fa1b9dce6c81477ffcfdfe1d40bddfd1252d"
source = "https://download.visualstudio.microsoft.com/download/pr/28271651-a8f6-41d6-9144-2d53f6c4aac4/bb29124818f370cd08c5c8cc8f8816bf/dotnet-runtime-2.2.3-linux-x64.tar.gz/archive/.tar.gz"
source_sha256 = "ae4aeb1e96c447b59ee9e9a2d08b6c9ec7a82bc06222819828ec165d704f05e8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime.2.2.3.linux-amd64-cflinuxfs3-4f43b75b.tar.xz"
version = "2.2.3"

[[metadata.dependencies]]
id = "dotnet-runtime"
sha256 = "62657e5f8c231adb266718329c7e50dac203385666c8fae5a0761f606359e9c5"
source = "https://download.visualstudio.microsoft.com/download/pr/853048a3-764a-4b4d-a608-c6144a84f257/99c5cb1ea145f9dc3c2bbd093c682c9b/dotnet-runtime-2.2.4-linux-x64.tar.gz/archive/.tar.gz"
source_sha256 = "0e494df7a3936ac59c17de3b91d928bb3ab3cdd1e6734d581ad4774f551ca239"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime.2.2.4.linux-amd64-cflinuxfs3-62657e5f.tar.xz"
version = "2.2.4"

[[metadata.dependencies]]
id = "dotnet-runtime"
sha256 = "9b0680d0a193ff5b89a8bc8a04ec2dd56aecc6321b5b57a185ad9f1ccc7ee77d"
source = "https://download.visualstudio.microsoft.com/download/pr/21968111-f65e-48c7-9c35-8b40de4af06c/66b7a2c7b92b54bd3311f4509cc9b9ed/dotnet-runtime-2.2.5-linux-x64.tar.gz/archive/.tar.gz"
source_sha256 = "a49ebecf9b1a4cadd47e4db65ae63425b94be75628314107def3abf52d5d0221"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime.2.2.5.linux-amd64-cflinuxfs3-9b0680d0.tar.xz"
version = "2.2.5"

[[metadata.dependencies]]
id = "dotnet-runtime"
sha256 = "915829b4fe61f0770f419df17febd38aaf228e5e796039a1e03947064d79f2f1"
source = "https://github.com/dotnet/cli/archive/3e0e612cb176daae0fce6ca54608d40428c9d27e.tar.gz"
source_sha256 = "e7a0d34b933d2dcac5d7536ab850f75af967b52567c82cd75e36e7d8145c9c2e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime.2.2.6.linux-amd64-cflinuxfs3-915829b4.tar.xz"
version = "2.2.6"

[[metadata.dependencies]]
id = "dotnet-runtime"
sha256 = "4d6dfb78b9efc3fe4ad5fe351daedba1097994e417517ffb3f461d9fe22f2169"
source = "https://github.com/dotnet/cli/archive/7a42b83262bb2b52804a2c14b4fad289d794c8be.tar.gz"
source_sha256 = "0b4a86f13d63418636762a997ecac5acd5ce5a8d59ff28f8a0f3e7a0c701ff4e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime.2.2.7.linux-amd64-cflinuxfs3-4d6dfb78.tar.xz"
version = "2.2.7"

[[metadata.dependency_deprecation_dates]]
date = 2021-08-21T00:00:00Z
link = "https://dotnet.microsoft.com/platform/support/policy/dotnet-core"
name = "dotnet-runtime"
version_line = "2.1.x"

[[metadata.dependency_deprecation_dates]]
date = 2019-12-23T00:00:00Z
link = "https://dotnet.microsoft.com/platform/support/policy/dotnet-core"
name = "dotnet-runtime"
version_line = "2.2.x"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
