api = "0.2"

[buildpack]
  id = "paketo-buildpacks/dotnet-core-runtime"
  name = "Paketo .NET Core Runtime Buildpack"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-runtime"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-21T00:00:00Z"
    id = "dotnet-runtime"
    sha256 = "841c94bf12c0f6410c30191c7d647c2459704c6393fc0d94734748c61766e57d"
    source = "https://download.visualstudio.microsoft.com/download/pr/5c00bafe-4ead-4e9a-82b6-884a9727e751/fdb7f6701e556d89b6884037cc9983cb/dotnet-runtime-2.1.26-linux-x64.tar.gz"
    source_sha256 = "2a7e4d28c9ab479570e5d351257796db8fa1d13a95092eeebf3934260b9a7a6e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_2.1.26_linux_x64_any-stack_841c94bf.tar.xz"
    version = "2.1.26"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-21T00:00:00Z"
    id = "dotnet-runtime"
    sha256 = "7f73229433859bbe1e383969e8db07ce8fef1ec1bea53507484fa606600fc66b"
    source = "https://download.visualstudio.microsoft.com/download/pr/f7eb39c4-484d-4e01-bd41-b4fe6794cd82/ff5c2799f30ea6dd19964c5c90780dba/dotnet-runtime-2.1.27-linux-x64.tar.gz"
    source_sha256 = "9d4e8c6c65939dd755e51e11f855f09c187d756b8bb6476ffb0419e539e57f5a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_2.1.27_linux_x64_any-stack_7f732294.tar.xz"
    version = "2.1.27"

  [[metadata.dependencies]]
    deprecation_date = "2022-12-04T00:00:00Z"
    id = "dotnet-runtime"
    sha256 = "9fef5f6bd7643acacf99271b03436253d10004308b94f1f5e39e48a6181477d9"
    source = "https://download.visualstudio.microsoft.com/download/pr/4e5f17fa-fa56-40bc-bf3d-fd6abc91d0ad/08bd80f3751c0ac602dd41dc2534265e/dotnet-runtime-3.1.14-linux-x64.tar.gz"
    source_sha256 = "666cb2148c1096d95339d1732f4420b633d1bb5532b9f3b1d2f8cfc15930e670"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_3.1.14_linux_x64_any-stack_9fef5f6b.tar.xz"
    version = "3.1.14"

  [[metadata.dependencies]]
    deprecation_date = "2022-12-04T00:00:00Z"
    id = "dotnet-runtime"
    sha256 = "9d15c9f97da76f0d37d106e3ffa82d1ecc1c239a822d8fd6d4c24d8d12630702"
    source = "https://download.visualstudio.microsoft.com/download/pr/692284f9-e1e7-4b31-9191-cd8043441024/ac45c17d4327b1f992b7fe3956a99129/dotnet-runtime-3.1.15-linux-x64.tar.gz"
    source_sha256 = "cf8017acab943d8ad048b5891bdd4acd041440ecfc5b468707cc7d987740098a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_3.1.15_linux_x64_any-stack_9d15c9f9.tar.xz"
    version = "3.1.15"

  [[metadata.dependencies]]
    id = "dotnet-runtime"
    sha256 = "e4c3d01f6eff1a442023841c309a4c8f2e9091eddb3bcefb4c7de98c7653a3ca"
    source = "https://download.visualstudio.microsoft.com/download/pr/6f26a190-5979-4fc4-b67a-df4e5b263e39/39e43561651183bb731ee6f3290fdcff/dotnet-runtime-5.0.5-linux-x64.tar.gz"
    source_sha256 = "64d33c50065e071205f6ef3b26d3c28eaecbeade2bdc3e96ed34d53e329b51ea"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_5.0.5_linux_x64_any-stack_e4c3d01f.tar.xz"
    version = "5.0.5"

  [[metadata.dependencies]]
    id = "dotnet-runtime"
    sha256 = "17fe758015e669e32ef02ac23dd7d2746a3ef32e957c033dd547a09da90a0d0c"
    source = "https://download.visualstudio.microsoft.com/download/pr/24b0e058-613e-415a-b624-09fb716cc129/91a51ddfd832aaa94cec5b117bf4db23/dotnet-runtime-5.0.6-linux-x64.tar.gz"
    source_sha256 = "944210e3dd120ec0f38f0f82d69f891cd76fd83c1c255673157a8dabee2c5580"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-runtime/dotnet-runtime_5.0.6_linux_x64_any-stack_17fe7580.tar.xz"
    version = "5.0.6"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-08-21T00:00:00Z
    link = "https://dotnet.microsoft.com/platform/support/policy/dotnet-core"
    name = "dotnet-runtime"
    version_line = "2.1.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2022-12-04T00:00:00Z
    link = "https://dotnet.microsoft.com/platform/support/policy/dotnet-core"
    name = "dotnet-runtime"
    version_line = "3.1.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
